name: weatherwise
description: "A smart weather companion app built with Flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Networking
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Location Services
  geolocator:  ^11.0.0
  geocoding: ^2.1.1
  permission_handler: ^11.1.0
  
  # UI & Animations
  lottie: ^3.0.0
  shimmer: ^3.0.0
  animate_do: ^3.1.2
  flutter_animate: ^4.3.0
  
  # Charts
  fl_chart: ^0.66.0
  
  # Images & Icons
  cached_network_image:  ^3.3.1
  
  # Utilities
  intl: ^0.19.0
  freezed_annotation: ^2.4.1
  equatable: ^2.0.5
  uuid: ^4.2.1
  
  # Notifications
  flutter_local_notifications: ^17.1.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.6
  riverpod_generator: ^2.3.9
  freezed:  ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/animations/
    - assets/images/